//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Localization.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Localization.Menu.MenuStrings", typeof(MenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        public static string aboutToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aligment.
        /// </summary>
        public static string aligment_Text {
            get {
                return ResourceManager.GetString("aligment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Benchmark.
        /// </summary>
        public static string Benchmark_Text {
            get {
                return ResourceManager.GetString("Benchmark.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bug reporting.
        /// </summary>
        public static string BugReporting_Text {
            get {
                return ResourceManager.GetString("BugReporting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Changelog.
        /// </summary>
        public static string Changelog_Text {
            get {
                return ResourceManager.GetString("Changelog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string chart3dToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("chart3dToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string chartToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("chartToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color_Text {
            get {
                return ResourceManager.GetString("color.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color assignment mode.
        /// </summary>
        public static string colorAssignmentToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("colorAssignmentToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string complexChartToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("complexChartToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Constants.
        /// </summary>
        public static string constantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("constantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countour lines mode.
        /// </summary>
        public static string contourLinesMode_Text {
            get {
                return ResourceManager.GetString("contourLinesMode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string copyToolStripButton_Text {
            get {
                return ResourceManager.GetString("copyToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string copyToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("copyToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        public static string cutToolStripButton_Text {
            get {
                return ResourceManager.GetString("cutToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        public static string cutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCT.
        /// </summary>
        public static string DCT_Text {
            get {
                return ResourceManager.GetString("DCT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Cosine Transform.
        /// </summary>
        public static string DCT_ToolTipText {
            get {
                return ResourceManager.GetString("DCT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHT.
        /// </summary>
        public static string DHT_Text {
            get {
                return ResourceManager.GetString("DHT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Hartley Transform.
        /// </summary>
        public static string DHT_ToolTipText {
            get {
                return ResourceManager.GetString("DHT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DST.
        /// </summary>
        public static string DST_Text {
            get {
                return ResourceManager.GetString("DST.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrete Sine Transform.
        /// </summary>
        public static string DST_ToolTipText {
            get {
                return ResourceManager.GetString("DST.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string edit_Text {
            get {
                return ResourceManager.GetString("edit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit properties....
        /// </summary>
        public static string editProperties_Text {
            get {
                return ResourceManager.GetString("editProperties.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string editToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("editToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Elementary functions.
        /// </summary>
        public static string elementaryFunctionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("elementaryFunctionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal axes.
        /// </summary>
        public static string equalAxes_Text {
            get {
                return ResourceManager.GetString("equalAxes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string exitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        public static string exponentiationToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exponentiationToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export_Text {
            get {
                return ResourceManager.GetString("export.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Features.
        /// </summary>
        public static string Features_Text {
            get {
                return ResourceManager.GetString("Features.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        public static string FFT_Text {
            get {
                return ResourceManager.GetString("FFT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Fourier Transform.
        /// </summary>
        public static string FFT_ToolTip_Text {
            get {
                return ResourceManager.GetString("FFT.ToolTip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FHT.
        /// </summary>
        public static string FHT_Text {
            get {
                return ResourceManager.GetString("FHT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Hilbert Transform.
        /// </summary>
        public static string FHT_ToolTipText {
            get {
                return ResourceManager.GetString("FHT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi&amp;le.
        /// </summary>
        public static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit axes.
        /// </summary>
        public static string fitAxes_Text {
            get {
                return ResourceManager.GetString("fitAxes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string fullscreenToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fullscreenToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Functions.
        /// </summary>
        public static string functionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("functionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He&amp;lp.
        /// </summary>
        public static string helpToolStripButton_Text {
            get {
                return ResourceManager.GetString("helpToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string helpToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("helpToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDCT.
        /// </summary>
        public static string IDCT_Text {
            get {
                return ResourceManager.GetString("IDCT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Discrete Cosine Transform.
        /// </summary>
        public static string IDCT_ToolTipText {
            get {
                return ResourceManager.GetString("IDCT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDST.
        /// </summary>
        public static string IDST_Text {
            get {
                return ResourceManager.GetString("IDST.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Discrete Sine Transform.
        /// </summary>
        public static string IDST_ToolTipText {
            get {
                return ResourceManager.GetString("IDST.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFFT.
        /// </summary>
        public static string IFFT_Text {
            get {
                return ResourceManager.GetString("IFFT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Fast Fourier Transform.
        /// </summary>
        public static string IFFT_ToolTipText {
            get {
                return ResourceManager.GetString("IFFT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFHT.
        /// </summary>
        public static string IFHT_Text {
            get {
                return ResourceManager.GetString("IFHT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Fast Hilbert Transform.
        /// </summary>
        public static string IFHT_ToolTipText {
            get {
                return ResourceManager.GetString("IFHT.ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_Text {
            get {
                return ResourceManager.GetString("Language.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend postions.
        /// </summary>
        public static string legendPositions_Text {
            get {
                return ResourceManager.GetString("legendPositions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logs.
        /// </summary>
        public static string Logs_Text {
            get {
                return ResourceManager.GetString("Logs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Mathematical constants.
        /// </summary>
        public static string mathematicalConstantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("mathematicalConstantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string newToolStripButton_Text {
            get {
                return ResourceManager.GetString("newToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string newToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("newToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string openToolStripButton_Text {
            get {
                return ResourceManager.GetString("openToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string openToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        public static string optionsToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string pasteToolStripButton_Text {
            get {
                return ResourceManager.GetString("pasteToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string pasteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pasteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Physical constants.
        /// </summary>
        public static string physicalConstantsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("physicalConstantsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placement.
        /// </summary>
        public static string placement_Text {
            get {
                return ResourceManager.GetString("placement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view.
        /// </summary>
        public static string printPreviewToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("printPreviewToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string printToolStripButton_Text {
            get {
                return ResourceManager.GetString("printToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string printToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("printToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        public static string redoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("redoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescale.
        /// </summary>
        public static string rescale_Text {
            get {
                return ResourceManager.GetString("rescale.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string runToolStripButton_Text {
            get {
                return ResourceManager.GetString("runToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        public static string saveAsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveAsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveToolStripButton_Text {
            get {
                return ResourceManager.GetString("saveToolStripButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        public static string selectAllToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("selectAllToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string series_Text {
            get {
                return ResourceManager.GetString("series.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Special functions.
        /// </summary>
        public static string specialFunctionsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("specialFunctionsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Thanks to.
        /// </summary>
        public static string ThanksTo_Text {
            get {
                return ResourceManager.GetString("ThanksTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string toolsToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("toolsToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran&amp;sform.
        /// </summary>
        public static string transformToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("transformToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type_Text {
            get {
                return ResourceManager.GetString("type.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        public static string undoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("undoToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
