//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computator.NET.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Computator.NET.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFile.
        /// </summary>
        public static string AddTab_NewFile {
            get {
                return ResourceManager.GetString("AddTab_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to chart.
        /// </summary>
        public static string AddToChart {
            get {
                return ResourceManager.GetString("AddToChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at line.
        /// </summary>
        public static string at_line {
            get {
                return ResourceManager.GetString("at_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta testers.
        /// </summary>
        public static string betaTesters {
            get {
                return ResourceManager.GetString("betaTesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bisection method.
        /// </summary>
        public static string bisection_method {
            get {
                return ResourceManager.GetString("bisection_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brent&apos;s method.
        /// </summary>
        public static string Brent_s_method {
            get {
                return ResourceManager.GetString("Brent_s_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broyden&apos;s method.
        /// </summary>
        public static string Broyden_s_method {
            get {
                return ResourceManager.GetString("Broyden_s_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug reporting.
        /// </summary>
        public static string BugReporting {
            get {
                return ResourceManager.GetString("BugReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centered five-point method.
        /// </summary>
        public static string centered_five_point_method {
            get {
                return ResourceManager.GetString("centered_five_point_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centered order-point method.
        /// </summary>
        public static string centered_order_point_method {
            get {
                return ResourceManager.GetString("centered_order_point_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart3D is not supported on Mono.
        /// </summary>
        public static string Chart3D_is_not_supported_on_Mono {
            get {
                return ResourceManager.GetString("Chart3D_is_not_supported_on_Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Check &quot;Real : f(x)&quot; mode.
        /// </summary>
        public static string Check__Real___f_x___mode {
            get {
                return ResourceManager.GetString("Check__Real___f_x___mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check chart area values.
        /// </summary>
        public static string CheckChartAreaValues {
            get {
                return ResourceManager.GetString("CheckChartAreaValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone tab.
        /// </summary>
        public static string Clone_tab {
            get {
                return ResourceManager.GetString("Clone_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        public static string Close_other_tabs {
            get {
                return ResourceManager.GetString("Close_other_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        public static string Close_tab {
            get {
                return ResourceManager.GetString("Close_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the left.
        /// </summary>
        public static string Close_tabs_to_the_left {
            get {
                return ResourceManager.GetString("Close_tabs_to_the_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the right.
        /// </summary>
        public static string Close_tabs_to_the_right {
            get {
                return ResourceManager.GetString("Close_tabs_to_the_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console output:.
        /// </summary>
        public static string ConsoleOutput {
            get {
                return ResourceManager.GetString("ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom functions errors.
        /// </summary>
        public static string Custom_functions_errors {
            get {
                return ResourceManager.GetString("Custom_functions_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string Delete_file {
            get {
                return ResourceManager.GetString("Delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        public static string Derivative {
            get {
                return ResourceManager.GetString("Derivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: .
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string Directory_tree_New_file {
            get {
                return ResourceManager.GetString("Directory_tree_New_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double exponential transformation.
        /// </summary>
        public static string double_exponential_transformation {
            get {
                return ResourceManager.GetString("double_exponential_transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw chart.
        /// </summary>
        public static string DrawChart {
            get {
                return ResourceManager.GetString("DrawChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string Error_code {
            get {
                return ResourceManager.GetString("Error_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in expression syntax. One of used functions does not exist / is incompatible with given arguments or you just made a mistake writing expression..
        /// </summary>
        public static string ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgumentsOrYouJustMadeAMistakeWritingExpression {
            get {
                return ResourceManager.GetString("ErrorInExpressionSyntaxOneOfUsedFunctionsDoesNotExistIsIncompatibleWithGivenArgum" +
                        "entsOrYouJustMadeAMistakeWritingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during startup.
        /// </summary>
        public static string Exception_during_startup {
            get {
                return ResourceManager.GetString("Exception_during_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occcured in.
        /// </summary>
        public static string Exception_occcured_in {
            get {
                return ResourceManager.GetString("Exception_occcured_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression errors.
        /// </summary>
        public static string Expression_errors {
            get {
                return ResourceManager.GetString("Expression_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression should not be empty!.
        /// </summary>
        public static string Expression_should_not_be_empty_ {
            get {
                return ResourceManager.GetString("Expression_should_not_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Real and complex functions charts
        ///
        /// - Real and complex calculator
        ///
        /// - Real functions numerical calculations including different methods
        ///
        /// - Over 107 Elementary functions
        ///
        /// - Over 141 Special functions
        ///
        /// - Over 21 Matrix functions and operations
        ///
        /// - Scripting language with power to easy computations including matrices
        ///
        /// - You can declare your own custom functions with scripting language.
        /// </summary>
        public static string featuresInclude {
            get {
                return ResourceManager.GetString("featuresInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finite difference formula.
        /// </summary>
        public static string finite_difference_formula {
            get {
                return ResourceManager.GetString("finite_difference_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function root.
        /// </summary>
        public static string Function_root {
            get {
                return ResourceManager.GetString("Function_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions &amp; Constants Details.
        /// </summary>
        public static string Functions_and_Constants_Details {
            get {
                return ResourceManager.GetString("Functions_and_Constants_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid..
        /// </summary>
        public static string GivenΕIsNotValid {
            get {
                return ResourceManager.GetString("GivenΕIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given ε is not valid. ε should be small positive number..
        /// </summary>
        public static string GivenΕIsNotValidΕShouldBeSmallPositiveNumber {
            get {
                return ResourceManager.GetString("GivenΕIsNotValidΕShouldBeSmallPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computator.NET is a special kind of numerical software that is fast and easy to use but not worse than others feature-wise..
        /// </summary>
        public static string GlobalConfig_assemblyDescription_Computator_NET_is_a_special_kind_of_numerical_software_that_is_fast_and_easy_to_use_but_not_worse_than_others_feature_wise_ {
            get {
                return ResourceManager.GetString("GlobalConfig_assemblyDescription_Computator_NET_is_a_special_kind_of_numerical_so" +
                        "ftware_that_is_fast_and_easy_to_use_but_not_worse_than_others_feature_wise_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart3D classes are based on code from High performance WPF 3D Chart rev.6 application on license.
        /// </summary>
        public static string GlobalConfig_others_Chart3D_classes_are_based_on_code_from_High_performance_WPF_3D_Chart_rev_6_application_on {
            get {
                return ResourceManager.GetString("GlobalConfig_others_Chart3D_classes_are_based_on_code_from_High_performance_WPF_3" +
                        "D_Chart_rev_6_application_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard algorithm for complex domain coloring.
        /// </summary>
        public static string GlobalConfig_others_standard_algorithm_for_complex_domain_coloring {
            get {
                return ResourceManager.GetString("GlobalConfig_others_standard_algorithm_for_complex_domain_coloring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png Image (.png)|*.png|Gif Image (.gif)|*.gif|JPEG Image (.jpeg)|*.jpeg|Bitmap Image (.bmp)|*.bmp|Tiff Image (.tiff)|*.tiff|Wmf Image (.wmf)|*.wmf.
        /// </summary>
        public static string Image_Filter {
            get {
                return ResourceManager.GetString("Image_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infinity-adaptive Gauss–Kronrod method.
        /// </summary>
        public static string infinity_adaptive_Gauss_Kronrod_method {
            get {
                return ResourceManager.GetString("infinity_adaptive_Gauss_Kronrod_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        public static string Integral {
            get {
                return ResourceManager.GetString("Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal errors.
        /// </summary>
        public static string Internal_errors {
            get {
                return ResourceManager.GetString("Internal_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label.
        ///.
        /// </summary>
        public static string InvalidLabel {
            get {
                return ResourceManager.GetString("InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s features include:.
        /// </summary>
        public static string ItSFeaturesInclude {
            get {
                return ResourceManager.GetString("ItSFeaturesInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label edit error.
        /// </summary>
        public static string Label_Edit_error {
            get {
                return ResourceManager.GetString("Label_Edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libraries used.
        /// </summary>
        public static string librariesUsed {
            get {
                return ResourceManager.GetString("librariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test cancelled by user..
        /// </summary>
        public static string MathFunctionsCalculationSpeedTestCancelledByUser {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math functions calculation speed test done succesfully! Check out your points results!.
        /// </summary>
        public static string MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults {
            get {
                return ResourceManager.GetString("MathFunctionsCalculationSpeedTestDoneSuccesfullyCheckOutYourPointsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test cancelled by user.
        /// </summary>
        public static string MemoryAllocationSpeedTestCancelledByUser {
            get {
                return ResourceManager.GetString("MemoryAllocationSpeedTestCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation speed test done succesfully, check out your points result.
        /// </summary>
        public static string MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult {
            get {
                return ResourceManager.GetString("MemoryAllocationSpeedTestDoneSuccesfullyCheckOutYourPointsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min value needs to be less than Max value..
        /// </summary>
        public static string Min_value_needs_to_be_less_than_Max_value {
            get {
                return ResourceManager.GetString("Min_value_needs_to_be_less_than_Max_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monte Carlo method.
        /// </summary>
        public static string Monte_Carlo_method {
            get {
                return ResourceManager.GetString("Monte_Carlo_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details: .
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string NativeCompiler_Column {
            get {
                return ResourceManager.GetString("NativeCompiler_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string NativeCompiler_error {
            get {
                return ResourceManager.GetString("NativeCompiler_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string NativeCompiler_Line {
            get {
                return ResourceManager.GetString("NativeCompiler_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string NativeCompiler_warning {
            get {
                return ResourceManager.GetString("NativeCompiler_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs to be greater than.
        /// </summary>
        public static string NeedsToBeGreaterThan {
            get {
                return ResourceManager.GetString("NeedsToBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs to be less than.
        /// </summary>
        public static string NeedsToBeLessThan {
            get {
                return ResourceManager.GetString("NeedsToBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        public static string New_tab {
            get {
                return ResourceManager.GetString("New_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function to invoke.
        /// </summary>
        public static string NoFunctionToInvoke {
            get {
                return ResourceManager.GetString("NoFunctionToInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-adaptive Gauss–Kronrod method.
        /// </summary>
        public static string non_adaptive_Gauss_Kronrod_method {
            get {
                return ResourceManager.GetString("non_adaptive_Gauss_Kronrod_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps should be small, default is 6.
        /// </summary>
        public static string Number_of_steps_should_be_small__default_is_6 {
            get {
                return ResourceManager.GetString("Number_of_steps_should_be_small__default_is_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Real mode is supported in Numerical calculations right now, more to come in next versions!.
        /// </summary>
        public static string Only_Real_mode_is_supported_in_Numerical_calculations_right_now__more_to_come_in_next_versions_ {
            get {
                return ResourceManager.GetString("Only_Real_mode_is_supported_in_Numerical_calculations_right_now__more_to_come_in_" +
                        "next_versions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or even better report them on project site, using link below.
        /// </summary>
        public static string Or_even_better_report_them_on_project_site__using_link_below {
            get {
                return ResourceManager.GetString("Or_even_better_report_them_on_project_site__using_link_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other contributors.
        /// </summary>
        public static string otherContributors {
            get {
                return ResourceManager.GetString("otherContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any bugs to Paweł Troka - pawel.troka@outlook.com.
        /// </summary>
        public static string PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk {
            get {
                return ResourceManager.GetString("PleaseReportAnyBugsToPawełTrokaPtrokaFizykaDk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Points!.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Thread Exception.
        /// </summary>
        public static string Program_Application_ThreadException_Unhandled_Thread_Exception {
            get {
                return ResourceManager.GetString("Program_Application_ThreadException_Unhandled_Thread_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try installing font!.
        /// </summary>
        public static string Program_CurrentDomain_UnhandledException_Try_installing_font_ {
            get {
                return ResourceManager.GetString("Program_CurrentDomain_UnhandledException_Try_installing_font_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rectangle method.
        /// </summary>
        public static string rectangle_method {
            get {
                return ResourceManager.GetString("rectangle_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        public static string Rename_file {
            get {
                return ResourceManager.GetString("Rename_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  result: .
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romberg&apos;s method.
        /// </summary>
        public static string Romberg_s_method {
            get {
                return ResourceManager.GetString("Romberg_s_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script errors.
        /// </summary>
        public static string Script_errors {
            get {
                return ResourceManager.GetString("Script_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secant method.
        /// </summary>
        public static string secant_method {
            get {
                return ResourceManager.GetString("secant_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secant Newton Raphson method.
        /// </summary>
        public static string secant_Newton_Raphson_method {
            get {
                return ResourceManager.GetString("secant_Newton_Raphson_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpson&apos;s method.
        /// </summary>
        public static string Simpson_s_method {
            get {
                return ResourceManager.GetString("Simpson_s_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source:.
        /// </summary>
        public static string Source_ {
            get {
                return ResourceManager.GetString("Source_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to:.
        /// </summary>
        public static string SpecialThanksTo {
            get {
                return ResourceManager.GetString("SpecialThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stable finite difference formula.
        /// </summary>
        public static string stable_finite_difference_formula {
            get {
                return ResourceManager.GetString("stable_finite_difference_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        public static string Syntax_error {
            get {
                return ResourceManager.GetString("Syntax_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invalid characters are: &apos;@&apos;,&apos;.&apos;, &apos;,&apos;, &apos;!&apos;.
        /// </summary>
        public static string The_invalid_characters_are {
            get {
                return ResourceManager.GetString("The_invalid_characters_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label cannot be blank.
        /// </summary>
        public static string The_label_cannot_be_blank {
            get {
                return ResourceManager.GetString("The_label_cannot_be_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translators.
        /// </summary>
        public static string translators {
            get {
                return ResourceManager.GetString("translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trapezoidal method.
        /// </summary>
        public static string trapezoidal_method {
            get {
                return ResourceManager.GetString("trapezoidal_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two-point finite difference formula.
        /// </summary>
        public static string two_point_finite_difference_formula {
            get {
                return ResourceManager.GetString("two_point_finite_difference_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled UI Exception.
        /// </summary>
        public static string Unhandled_UI_Exception {
            get {
                return ResourceManager.GetString("Unhandled_UI_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning_ {
            get {
                return ResourceManager.GetString("Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   |  X/Y ratio = {0}  |.
        /// </summary>
        public static string XYRatio0 {
            get {
                return ResourceManager.GetString("XYRatio0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have any logs yet..
        /// </summary>
        public static string You_dont_have_any_logs_yet_ {
            get {
                return ResourceManager.GetString("You_dont_have_any_logs_yet_", resourceCulture);
            }
        }
    }
}
