language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.16.0
      dotnet: 2.0
      env: build_config=Release
      env: netmoniker=net461
    - os: linux
      dist: trusty
      sudo: required
      mono: 5.16.0
      dotnet: 2.0
      env: build_config=Debug
      env: netmoniker=net461
    - os: osx
      osx_image: xcode9.4
      sudo: required
      mono: 5.16.0
      dotnet: 2.0
      env: build_config=Release
      env: netmoniker=net461
    - os: osx
      osx_image: xcode9.4
      sudo: required
      mono: 5.16.0
      dotnet: 2.0
      env: build_config=Debug
      env: netmoniker=net461



#before_install:

before_script:
  - chmod +x build.sh
  - ./build.sh --target=Restore

script:
  - ./build.sh --target=Build

after_script:
  - travis_wait 60 ./build.sh --target=AllTests
  - if [ "$TRAVIS_OS_NAME" != "linux" && "$TRAVIS_OS_NAME" != "osx" ]; then travis_wait 60 ./build.sh --target=Upload-Coverage; fi